/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexus;

/**
 *
 * @author Daniel Caballero
 */
public class AuditAndReporting extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuditAndReporting.class.getName());

    /**
     * Creates new form AuditAndReporting
     */
    public AuditAndReporting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back_Button = new javax.swing.JLabel();
        AccountManagement_Button = new javax.swing.JLabel();
        TransactionLogs_Button = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 607));

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 607));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 607));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 24, 150, 49));

        AccountManagement_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountManagement_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(AccountManagement_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 153, 104, 104));

        TransactionLogs_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionLogs_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(TransactionLogs_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 294, 104, 104));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/image/AuditAndReporting.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_ButtonMouseClicked
        AdminPanel page5 = new AdminPanel();
        page5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_ButtonMouseClicked

    private void AccountManagement_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountManagement_ButtonMouseClicked
        AdminAccount page5_3 = new AdminAccount();
        page5_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccountManagement_ButtonMouseClicked

    private void TransactionLogs_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionLogs_ButtonMouseClicked
        TransactionLogs page5_1 = new TransactionLogs();
        page5_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionLogs_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuditAndReporting().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountManagement_Button;
    private javax.swing.JLabel Back_Button;
    private javax.swing.JLabel TransactionLogs_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
