/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexus;

/**
 *
 * @author Daniel Caballero
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginEmail_TextField = new javax.swing.JTextField();
        LoginPassword_TextField = new javax.swing.JTextField();
        Login_Button = new javax.swing.JLabel();
        SignUp_Label = new javax.swing.JLabel();
        Admin_Lever = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 607));

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 607));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 607));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginEmail_TextField.setBackground(new java.awt.Color(187, 134, 252));
        LoginEmail_TextField.setText("jTextField2");
        LoginEmail_TextField.setBorder(null);
        LoginEmail_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginEmail_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(LoginEmail_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 220, 320, 40));

        LoginPassword_TextField.setBackground(new java.awt.Color(187, 134, 252));
        LoginPassword_TextField.setText("jTextField1");
        LoginPassword_TextField.setBorder(null);
        LoginPassword_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPassword_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(LoginPassword_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 314, 320, 40));

        Login_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 170, 50));

        SignUp_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUp_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(SignUp_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 465, 50, 20));

        Admin_Lever.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admin_LeverMouseClicked(evt);
            }
        });
        jPanel1.add(Admin_Lever, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/image/LoginPage2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginPassword_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPassword_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPassword_TextFieldActionPerformed

    private void Login_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_ButtonMouseClicked
        UserDashboard page4 = new UserDashboard();
        page4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login_ButtonMouseClicked

    private void SignUp_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUp_LabelMouseClicked
        SignUp page2 = new SignUp();
        page2.setVisible(true);
    }//GEN-LAST:event_SignUp_LabelMouseClicked

    private void LoginEmail_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginEmail_TextFieldActionPerformed
        
    }//GEN-LAST:event_LoginEmail_TextFieldActionPerformed

    private void Admin_LeverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admin_LeverMouseClicked
        AdminPanel page5 = new AdminPanel();
        page5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Admin_LeverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_Lever;
    private javax.swing.JTextField LoginEmail_TextField;
    private javax.swing.JTextField LoginPassword_TextField;
    private javax.swing.JLabel Login_Button;
    private javax.swing.JLabel SignUp_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
