/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexus;

/**
 *
 * @author Daniel Caballero
 */
public class SignUpPage2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage2.class.getName());

    /**
     * Creates new form SignUpPage2
     */
    public SignUpPage2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Address_TextField = new javax.swing.JTextField();
        Gender_TextField = new javax.swing.JTextField();
        GovernmentIssuedID_TextField = new javax.swing.JTextField();
        BirthDate_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Login_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(521, 607));
        setMinimumSize(new java.awt.Dimension(521, 607));
        setPreferredSize(new java.awt.Dimension(521, 607));

        jPanel1.setMaximumSize(new java.awt.Dimension(521, 607));
        jPanel1.setMinimumSize(new java.awt.Dimension(521, 607));
        jPanel1.setPreferredSize(new java.awt.Dimension(521, 607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Address_TextField.setBackground(new java.awt.Color(187, 134, 252));
        Address_TextField.setText("jTextField1");
        Address_TextField.setBorder(null);
        jPanel1.add(Address_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 112, 320, 40));

        Gender_TextField.setBackground(new java.awt.Color(187, 134, 252));
        Gender_TextField.setText("jTextField2");
        Gender_TextField.setBorder(null);
        jPanel1.add(Gender_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 192, 320, 39));

        GovernmentIssuedID_TextField.setBackground(new java.awt.Color(187, 134, 252));
        GovernmentIssuedID_TextField.setText("jTextField1");
        GovernmentIssuedID_TextField.setBorder(null);
        jPanel1.add(GovernmentIssuedID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 272, 320, 39));

        BirthDate_TextField.setBackground(new java.awt.Color(187, 134, 252));
        BirthDate_TextField.setText("jTextField1");
        BirthDate_TextField.setBorder(null);
        jPanel1.add(BirthDate_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 352, 320, 39));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 422, 148, 46));

        Login_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(Login_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 480, 37, 16));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/image/SignUpPage2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void Login_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_LabelMouseClicked
        Login newpage = new Login();
        newpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_TextField;
    private javax.swing.JTextField BirthDate_TextField;
    private javax.swing.JTextField Gender_TextField;
    private javax.swing.JTextField GovernmentIssuedID_TextField;
    private javax.swing.JLabel Login_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
