/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexus;

/**
 *
 * @author Daniel Caballero
 */
public class SignUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FullName_TextField = new javax.swing.JTextField();
        Password_TextField = new javax.swing.JTextField();
        ConfirmPassword_TextField = new javax.swing.JTextField();
        Email_TextField = new javax.swing.JTextField();
        ContactInfo_TextField = new javax.swing.JTextField();
        NextPage_Button = new javax.swing.JLabel();
        Login_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(522, 607));
        setMinimumSize(new java.awt.Dimension(522, 607));
        setSize(new java.awt.Dimension(522, 607));

        jPanel1.setMaximumSize(new java.awt.Dimension(522, 607));
        jPanel1.setPreferredSize(new java.awt.Dimension(522, 607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FullName_TextField.setBackground(new java.awt.Color(187, 134, 252));
        FullName_TextField.setText("jTextField1");
        FullName_TextField.setBorder(null);
        FullName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullName_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(FullName_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 112, 320, 39));

        Password_TextField.setBackground(new java.awt.Color(187, 134, 252));
        Password_TextField.setText("jTextField1");
        Password_TextField.setToolTipText("");
        Password_TextField.setBorder(null);
        jPanel1.add(Password_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 195, 320, 39));

        ConfirmPassword_TextField.setBackground(new java.awt.Color(187, 134, 252));
        ConfirmPassword_TextField.setText("jTextField1");
        ConfirmPassword_TextField.setBorder(null);
        jPanel1.add(ConfirmPassword_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 280, 319, 39));

        Email_TextField.setBackground(new java.awt.Color(187, 134, 252));
        Email_TextField.setText("jTextField1");
        Email_TextField.setBorder(null);
        jPanel1.add(Email_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 363, 320, 39));

        ContactInfo_TextField.setBackground(new java.awt.Color(187, 134, 252));
        ContactInfo_TextField.setText("jTextField1");
        ContactInfo_TextField.setBorder(null);
        jPanel1.add(ContactInfo_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 447, 320, 39));
        ContactInfo_TextField.getAccessibleContext().setAccessibleName("");

        NextPage_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextPage_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(NextPage_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 503, 150, 40));

        Login_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(Login_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 560, 38, 16));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/image/SignUpPage.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FullName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullName_TextFieldActionPerformed

    private void Login_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_LabelMouseClicked
        Login newpage = new Login();
        newpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login_LabelMouseClicked

    private void NextPage_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextPage_ButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NextPage_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmPassword_TextField;
    private javax.swing.JTextField ContactInfo_TextField;
    private javax.swing.JTextField Email_TextField;
    private javax.swing.JTextField FullName_TextField;
    private javax.swing.JLabel Login_Label;
    private javax.swing.JLabel NextPage_Button;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
