/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nexus;

/**
 *
 * @author Daniel Caballero
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ApplyNewAccount_Button = new javax.swing.JLabel();
        CashTransfer_Button = new javax.swing.JLabel();
        Withdraw_Button = new javax.swing.JLabel();
        Deposit_Button = new javax.swing.JLabel();
        Menu_Button = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 607));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ApplyNewAccount_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApplyNewAccount_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ApplyNewAccount_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 113, 95, 96));

        CashTransfer_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CashTransfer_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(CashTransfer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 235, 95, 96));

        Withdraw_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Withdraw_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Withdraw_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 358, 95, 96));

        Deposit_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Deposit_ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(Deposit_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 95, 96));
        jPanel1.add(Menu_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 22, 130, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/image/UserDashboard.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ApplyNewAccount_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyNewAccount_ButtonMouseClicked
        NewAccount page6 = new NewAccount();
        page6.setVisible(true);
    }//GEN-LAST:event_ApplyNewAccount_ButtonMouseClicked

    private void CashTransfer_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashTransfer_ButtonMouseClicked
        Transfer page7 = new Transfer();
        page7.setVisible(true);
    }//GEN-LAST:event_CashTransfer_ButtonMouseClicked

    private void Withdraw_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Withdraw_ButtonMouseClicked
        Withdraw page8 = new Withdraw();
        page8.setVisible(true);
    }//GEN-LAST:event_Withdraw_ButtonMouseClicked

    private void Deposit_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Deposit_ButtonMouseClicked
        Deposit page9 = new Deposit();
        page9.setVisible(true);
    }//GEN-LAST:event_Deposit_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApplyNewAccount_Button;
    private javax.swing.JLabel CashTransfer_Button;
    private javax.swing.JLabel Deposit_Button;
    private javax.swing.JLabel Menu_Button;
    private javax.swing.JLabel Withdraw_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
